### ISSUE TITLE
Unable to get the current PPKPeer object

### ISSUE THREAD

**Issue by twof** [Uepaa-AG/p2pkit-quickstart-ios#5]
Myself and the rest of my team found your sdk and used it during a hackathon this weekend. We thought the sdk was a breeze to use, aside from one minor issue. There doesn't seem to be a way to access the current PPKPeer instance and we felt that that one addition would have made utilizing p2pkit even easier. Are there any plans to make this happen? 
Here's the (unfinished) project we worked on: https://github.com/twof/Stalk
Thanks for the awesome tool!

**Comment by emimh** [comment]
Thanks for your feedback and using our SDK!
As I understand, you want your own info accessible accessible through a PPKPeer object, correct? Currently we do not have any plans to add this. Maybe you can elaborate a bit more what you mean exactly and how this could be useful. Thanks.

**Comment by twof** [comment]
For our purposes in particular, we needed our own information to pass along to other devices. It was a UID we needed if I remember correctly along with a few other pieces of info that I'm sure I'm forgetting. I'm sorry I couldn't be more helpful because the hackathon was a few weeks ago now. I'd be happy to dig deeper for more info if that would be helpful.
