### ISSUE TITLE
P2P GEO Discovery - weak definition

### ISSUE THREAD

**Issue by Souness11** [Uepaa-AG/p2pkit-quickstart-ios#6]
Hello,
In the documentation you have that:
 – GeoPeerDiscovered:
Reports GEO discovery of a nearby peer (i.e. your reported GEO location is ‘nearby’ the reported GEO location of the peer).

One question: 
What number is ‘nearby’. Can I somehow define that geoPeerDiscovered should be called when a peer is like 100m or 50m away from me? 

Thanks.

**Comment by emimh** [comment]
GEO peers are determined nearby when there are less than ~300m away from your current location. Currently there is now way for you to define/change this distance in the SDK.
